site_name: P3
theme:
  favicon: static/keyboard.png
  font:
    code: Ubuntu Mono
    text: Space Mono
  logo: static/keyboard.png
  name: material
  palette:
    primary: black
    scheme: slate
plugins:
  - entangled
markdown_extensions:
  - pymdownx.superfences
